# Generated by Django 2.2.5 on 2019-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('volume_price', models.IntegerField()),
            ],
            options={
                'ordering': ['-volume_price'],
            },
        ),
    ]
