# Generated by Django 2.2.5 on 2019-09-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume_price',
            field=models.FloatField(),
        ),
    ]
