# Generated by Django 2.2.5 on 2019-09-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190926_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='name',
            new_name='currency',
        ),
    ]
