# Generated by Django 2.2.6 on 2019-10-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190926_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={},
        ),
        migrations.RemoveField(
            model_name='coin',
            name='volume_price',
        ),
        migrations.AddField(
            model_name='coin',
            name='korean',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
