# Generated by Django 2.2.6 on 2019-10-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191010_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
